version: '3'

volumes:
  pgdata12: {}

networks:
  backend1:
    name: backend1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

services:
  db:
    container_name: db
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    networks:
      backend1:
        ipv4_address: 172.21.0.2
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - pgdata12:/var/lib/postgresql/data

  module:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      backend1:
        ipv4_address: 172.21.0.3
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    links:
      - db:db
    depends_on:
      - db
