version: '3'

services:
  module:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
