version: '3'

services:
  module:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"


networks:
  backend:
    driver: bridge
